-- =====================================================
-- INSERCIÓN DE MEDICAMENTOS COMPLETOS CON DATOS REALES
-- 100 medicamentos con información verídica
-- =====================================================

-- Primero, insertamos las categorías
INSERT INTO categorias_medicamentos (nombre, descripcion) VALUES
  ('Analgésicos', 'Medicamentos para aliviar el dolor'),
  ('Antiinflamatorios', 'Reducen la inflamación y el dolor'),
  ('Antibióticos', 'Tratan infecciones bacterianas'),
  ('Antihistamínicos', 'Tratan alergias y síntomas relacionados'),
  ('Antihipertensivos', 'Controlan la presión arterial alta'),
  ('Antidiabéticos', 'Controlan los niveles de glucosa en sangre'),
  ('Anticoagulantes', 'Previenen la formación de coágulos'),
  ('Antiácidos', 'Neutralizan el ácido estomacal'),
  ('Broncodilatadores', 'Facilitan la respiración'),
  ('Antidepresivos', 'Tratan la depresión y trastornos del ánimo'),
  ('Ansiolíticos', 'Reducen la ansiedad'),
  ('Vitaminas y Suplementos', 'Complementos nutricionales'),
  ('Antivirales', 'Tratan infecciones virales'),
  ('Diuréticos', 'Aumentan la eliminación de líquidos'),
  ('Corticoides', 'Reducen inflamación e inmunosupresión')
ON CONFLICT (nombre) DO NOTHING;

-- Ahora insertamos los medicamentos con información detallada y URLs de imágenes reales

-- ANALGÉSICOS (1-5)
INSERT INTO medicamentos (nombre, descripcion, categoria_id, imagen_url, dosis_recomendada, via_administracion, indicaciones, contraindicaciones) VALUES

('Paracetamol 500mg', 'Analgésico y antipirético de uso común para dolor leve a moderado y fiebre', 
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Analgésicos' LIMIT 1), 
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '500-1000mg cada 6-8 horas (máximo 4g/día)', 'Oral',
  'Dolor de cabeza, dolor muscular, artritis leve, dolor de espalda, dolor dental, fiebre',
  'Enfermedad hepática severa, alcoholismo crónico, alergia al paracetamol'),

('Ibuprofeno 400mg', 'AINE con propiedades analgésicas, antiinflamatorias y antipiréticas',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Analgésicos' LIMIT 1),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '400mg cada 6-8 horas con alimentos (máximo 2.4g/día)', 'Oral',
  'Dolor muscular, dolor menstrual, artritis, dolor dental, fiebre, migraña',
  'Úlcera péptica activa, insuficiencia cardíaca severa, tercer trimestre del embarazo'),

('Naproxeno 500mg', 'AINE de acción prolongada para dolor e inflamación',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Analgésicos' LIMIT 1),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '500mg cada 12 horas con alimentos', 'Oral',
  'Artritis reumatoide, osteoartritis, espondilitis anquilosante, tendinitis, bursitis',
  'Úlcera péptica, insuficiencia renal severa, embarazo tercer trimestre'),

('Tramadol 50mg', 'Analgésico opioide para dolor moderado a severo',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Analgésicos' LIMIT 1),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '50-100mg cada 6 horas según necesidad', 'Oral',
  'Dolor postoperatorio, dolor crónico, dolor oncológico moderado',
  'Depresión respiratoria, uso de IMAO, alcoholismo agudo, epilepsia no controlada'),

('Ketorolaco 10mg', 'AINE potente para dolor agudo de corta duración',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Analgésicos' LIMIT 1),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '10mg cada 6 horas por máximo 5 días', 'Oral',
  'Dolor postoperatorio, cólico renal, dolor agudo moderado a severo',
  'Úlcera péptica, insuficiencia renal, hemorragia activa, parto'),

-- ANTIINFLAMATORIOS (6-10)
('Diclofenaco 50mg', 'AINE potente para procesos inflamatorios',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiinflamatorios' LIMIT 1),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '50mg cada 8 horas con alimentos', 'Oral',
  'Artritis reumatoide, osteoartritis, espondilitis, dolor musculoesquelético',
  'Úlcera péptica activa, insuficiencia cardíaca, tercer trimestre embarazo'),

('Meloxicam 15mg', 'AINE selectivo con menos efectos gastrointestinales',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiinflamatorios' LIMIT 1),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '15mg una vez al día con alimentos', 'Oral',
  'Osteoartritis, artritis reumatoide, dolor crónico',
  'Úlcera péptica, insuficiencia renal severa, embarazo'),

('Celecoxib 200mg', 'Inhibidor selectivo de COX-2 para artritis',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiinflamatorios' LIMIT 1),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '200mg una o dos veces al día', 'Oral',
  'Osteoartritis, artritis reumatoide, espondilitis anquilosante',
  'Alergia a sulfonamidas, enfermedad cardiovascular severa, úlcera activa'),

('Piroxicam 20mg', 'AINE de acción prolongada para artritis',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiinflamatorios' LIMIT 1),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '20mg una vez al día', 'Oral',
  'Artritis reumatoide, osteoartritis, trastornos musculoesqueléticos',
  'Úlcera péptica, insuficiencia renal, embarazo'),

('Indometacina 25mg', 'AINE potente para inflamación severa',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiinflamatorios' LIMIT 1),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '25-50mg cada 8 horas con alimentos', 'Oral',
  'Artritis reumatoide, gota aguda, espondilitis anquilosante',
  'Úlcera péptica, insuficiencia cardíaca, epilepsia, parkinson'),

-- ANTIBIÓTICOS (11-20)
('Amoxicilina 500mg', 'Antibiótico de amplio espectro tipo penicilina',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antibióticos' LIMIT 1),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '500mg cada 8 horas por 7-10 días', 'Oral',
  'Infecciones respiratorias, otitis, sinusitis, infecciones urinarias, infecciones dentales',
  'Alergia a penicilinas, mononucleosis infecciosa'),

('Azitromicina 500mg', 'Antibiótico macrólido de dosis única diaria',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antibióticos' LIMIT 1),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '500mg día 1, luego 250mg días 2-5', 'Oral',
  'Neumonía, bronquitis, infecciones de piel, infecciones por clamidia',
  'Alergia a macrólidos, enfermedad hepática severa'),

('Ciprofloxacino 500mg', 'Fluoroquinolona de amplio espectro',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antibióticos' LIMIT 1),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '500mg cada 12 horas por 7-14 días', 'Oral',
  'Infecciones urinarias, prostatitis, infecciones gastrointestinales, sinusitis',
  'Menores de 18 años, embarazo, lactancia, miastenia gravis'),

('Cefalexina 500mg', 'Cefalosporina de primera generación',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antibióticos' LIMIT 1),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '500mg cada 6 horas por 7-14 días', 'Oral',
  'Infecciones de piel, infecciones respiratorias, otitis, infecciones urinarias',
  'Alergia a cefalosporinas o penicilinas'),

('Clindamicina 300mg', 'Antibiótico para infecciones por anaerobios',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antibióticos' LIMIT 1),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '300mg cada 6 horas por 7-10 días', 'Oral',
  'Infecciones de piel, infecciones dentales, infecciones óseas',
  'Colitis pseudomembranosa, enfermedad intestinal inflamatoria'),

('Doxiciclina 100mg', 'Tetraciclina de amplio espectro',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antibióticos' LIMIT 1),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '100mg cada 12 horas por 7-14 días', 'Oral',
  'Acné, infecciones respiratorias, enfermedad de Lyme, malaria profilaxis',
  'Embarazo, lactancia, menores de 8 años, insuficiencia hepática'),

('Metronidazol 500mg', 'Antibiótico para infecciones por anaerobios y parásitos',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antibióticos' LIMIT 1),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '500mg cada 8 horas por 7-10 días', 'Oral',
  'Infecciones abdominales, vaginosis bacteriana, giardiasis, amebiasis',
  'Primer trimestre embarazo, alcoholismo (efecto disulfiram)'),

('Trimetoprima-Sulfametoxazol 160/800mg', 'Combinación antibiótica de amplio espectro',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antibióticos' LIMIT 1),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '1 tableta cada 12 horas por 7-14 días', 'Oral',
  'Infecciones urinarias, bronquitis, neumonía por Pneumocystis',
  'Alergia a sulfonamidas, insuficiencia renal severa, embarazo'),

('Cefuroxima 500mg', 'Cefalosporina de segunda generación',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antibióticos' LIMIT 1),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '500mg cada 12 horas por 7-10 días', 'Oral',
  'Infecciones respiratorias, sinusitis, otitis, infecciones de piel',
  'Alergia a cefalosporinas'),

('Levofloxacino 500mg', 'Fluoroquinolona de amplio espectro',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antibióticos' LIMIT 1),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '500mg una vez al día por 7-14 días', 'Oral',
  'Neumonía, sinusitis, bronquitis, infecciones urinarias complicadas',
  'Menores de 18 años, embarazo, historia de tendinitis'),

-- ANTIHISTAMÍNICOS (26-30)
('Loratadina 10mg', 'Antihistamínico de segunda generación no sedante',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihistamínicos'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '10mg una vez al día', 'Oral',
  'Rinitis alérgica, urticaria, picazón, alergia estacional',
  'Hipersensibilidad a loratadina, insuficiencia hepática severa'),

('Cetirizina 10mg', 'Antihistamínico de segunda generación',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihistamínicos'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '10mg una vez al día', 'Oral',
  'Rinitis alérgica perenne y estacional, urticaria crónica',
  'Insuficiencia renal severa, hipersensibilidad'),

('Fexofenadina 180mg', 'Antihistamínico no sedante de larga duración',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihistamínicos'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '180mg una vez al día', 'Oral',
  'Rinitis alérgica, urticaria crónica idiopática',
  'Hipersensibilidad, insuficiencia renal severa'),

('Clorfeniramina 4mg', 'Antihistamínico de primera generación',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihistamínicos'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '4mg cada 6 horas', 'Oral',
  'Rinitis alérgica, urticaria, reacciones alérgicas leves',
  'Glaucoma, retención urinaria, asma aguda'),

('Desloratadina 5mg', 'Metabolito activo de loratadina, no sedante',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihistamínicos'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '5mg una vez al día', 'Oral',
  'Rinitis alérgica, urticaria crónica idiopática',
  'Hipersensibilidad, insuficiencia renal severa'),

-- ANTIHIPERTENSIVOS (31-40)
('Losartán 50mg', 'Antagonista de receptores de angiotensina II',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihipertensivos'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '50mg una vez al día, puede aumentar a 100mg', 'Oral',
  'Hipertensión arterial, protección renal en diabetes, insuficiencia cardíaca',
  'Embarazo, lactancia, estenosis bilateral de arteria renal'),

('Enalapril 10mg', 'Inhibidor de la enzima convertidora de angiotensina (IECA)',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihipertensivos'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '10mg una o dos veces al día', 'Oral',
  'Hipertensión arterial, insuficiencia cardíaca, disfunción ventricular izquierda',
  'Embarazo, lactancia, angioedema previo, estenosis bilateral renal'),

('Amlodipino 5mg', 'Bloqueador de canales de calcio',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihipertensivos'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '5-10mg una vez al día', 'Oral',
  'Hipertensión arterial, angina de pecho, enfermedad coronaria',
  'Estenosis aórtica severa, shock cardiogénico, hipersensibilidad'),

('Metoprolol 50mg', 'Beta-bloqueador cardioselectivo',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihipertensivos'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '50-100mg una o dos veces al día', 'Oral',
  'Hipertensión, angina, infarto agudo de miocardio, insuficiencia cardíaca',
  'Bradicardia severa, bloqueo AV, asma bronquial severa, shock cardiogénico'),

('Hidroclorotiazida 25mg', 'Diurético tiazídico',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihipertensivos'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '25mg una vez al día por la mañana', 'Oral',
  'Hipertensión arterial, edema, insuficiencia cardíaca leve',
  'Anuria, insuficiencia renal severa, hipopotasemia no corregida'),

('Valsartán 80mg', 'Antagonista de receptores de angiotensina II',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihipertensivos'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '80-160mg una vez al día', 'Oral',
  'Hipertensión arterial, insuficiencia cardíaca, post-infarto',
  'Embarazo, lactancia, estenosis bilateral de arteria renal'),

('Carvedilol 25mg', 'Beta-bloqueador no selectivo con propiedades vasodilatadoras',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihipertensivos'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '25mg dos veces al día con alimentos', 'Oral',
  'Hipertensión arterial, insuficiencia cardíaca, disfunción ventricular post-infarto',
  'Bradicardia severa, bloqueo AV, insuficiencia cardíaca descompensada'),

('Telmisartán 40mg', 'Antagonista de receptores de angiotensina II de larga duración',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihipertensivos'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '40-80mg una vez al día', 'Oral',
  'Hipertensión arterial, prevención cardiovascular',
  'Embarazo, lactancia, obstrucción biliar'),

('Atenolol 50mg', 'Beta-bloqueador cardioselectivo',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihipertensivos'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '50-100mg una vez al día', 'Oral',
  'Hipertensión arterial, angina de pecho, arritmias cardíacas',
  'Bradicardia severa, bloqueo cardíaco, asma bronquial'),

('Nifedipino 30mg', 'Bloqueador de canales de calcio de acción prolongada',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antihipertensivos'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '30-60mg una vez al día', 'Oral',
  'Hipertensión arterial, angina de pecho, fenómeno de Raynaud',
  'Shock cardiogénico, estenosis aórtica severa, infarto agudo reciente'),

-- ANTIDIABÉTICOS (41-50)
('Metformina 850mg', 'Biguanida, primera línea en diabetes tipo 2',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidiabéticos'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '850mg una o dos veces al día con alimentos', 'Oral',
  'Diabetes mellitus tipo 2, síndrome de ovario poliquístico',
  'Insuficiencia renal, acidosis metabólica, insuficiencia hepática severa'),

('Glibenclamida 5mg', 'Sulfonilurea de segunda generación',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidiabéticos'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '5mg una vez al día antes del desayuno', 'Oral',
  'Diabetes mellitus tipo 2 no controlada con dieta',
  'Diabetes tipo 1, insuficiencia renal o hepática severa, embarazo'),

('Sitagliptina 100mg', 'Inhibidor de DPP-4',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidiabéticos'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '100mg una vez al día', 'Oral',
  'Diabetes mellitus tipo 2 en combinación o monoterapia',
  'Diabetes tipo 1, cetoacidosis diabética, insuficiencia renal severa'),

('Glimepirida 2mg', 'Sulfonilurea de tercera generación',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidiabéticos'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '2-4mg una vez al día con desayuno', 'Oral',
  'Diabetes mellitus tipo 2',
  'Diabetes tipo 1, insuficiencia renal o hepática severa, embarazo'),

('Pioglitazona 30mg', 'Tiazolidinediona, sensibilizador de insulina',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidiabéticos'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '30mg una vez al día', 'Oral',
  'Diabetes mellitus tipo 2 en combinación',
  'Insuficiencia cardíaca, insuficiencia hepática, cáncer de vejiga activo'),

('Acarbosa 100mg', 'Inhibidor de alfa-glucosidasa',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidiabéticos'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '100mg tres veces al día con primer bocado', 'Oral',
  'Diabetes mellitus tipo 2, hiperglucemia postprandial',
  'Enfermedad intestinal inflamatoria, úlcera intestinal, insuficiencia renal'),

('Empagliflozina 10mg', 'Inhibidor de SGLT-2',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidiabéticos'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '10-25mg una vez al día', 'Oral',
  'Diabetes mellitus tipo 2, insuficiencia cardíaca con diabetes',
  'Insuficiencia renal severa, cetoacidosis diabética'),

('Linagliptina 5mg', 'Inhibidor de DPP-4',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidiabéticos'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '5mg una vez al día', 'Oral',
  'Diabetes mellitus tipo 2',
  'Diabetes tipo 1, cetoacidosis diabética, hipersensibilidad'),

('Repaglinida 1mg', 'Secretagogo de insulina de acción rápida',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidiabéticos'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '1-2mg antes de cada comida', 'Oral',
  'Diabetes mellitus tipo 2, hiperglucemia postprandial',
  'Diabetes tipo 1, insuficiencia hepática severa, cetoacidosis'),

('Canagliflozina 100mg', 'Inhibidor de SGLT-2',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidiabéticos'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '100mg una vez al día antes del desayuno', 'Oral',
  'Diabetes mellitus tipo 2, reducción de riesgo cardiovascular',
  'Insuficiencia renal severa, cetoacidosis, deshidratación'),

-- ANTICOAGULANTES (51-55)
('Warfarina 5mg', 'Anticoagulante oral antagonista de vitamina K',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Anticoagulantes'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  'Dosis ajustada según INR, usualmente 2-10mg/día', 'Oral',
  'Fibrilación auricular, trombosis venosa profunda, embolia pulmonar, válvulas cardíacas',
  'Hemorragia activa, embarazo, hipertensión no controlada severa'),

('Rivaroxabán 20mg', 'Anticoagulante oral directo, inhibidor del factor Xa',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Anticoagulantes'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '20mg una vez al día con alimentos', 'Oral',
  'Fibrilación auricular no valvular, trombosis venosa profunda, embolia pulmonar',
  'Hemorragia activa, insuficiencia renal severa, embarazo'),

('Apixabán 5mg', 'Anticoagulante oral directo, inhibidor del factor Xa',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Anticoagulantes'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '5mg dos veces al día', 'Oral',
  'Fibrilación auricular no valvular, prevención de trombosis',
  'Hemorragia activa, insuficiencia hepática severa, embarazo'),

('Dabigatrán 150mg', 'Anticoagulante oral directo, inhibidor directo de trombina',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Anticoagulantes'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '150mg dos veces al día', 'Oral',
  'Fibrilación auricular no valvular, prevención de ictus',
  'Hemorragia activa, insuficiencia renal severa, prótesis valvular mecánica'),

('Clopidogrel 75mg', 'Antiagregante plaquetario',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Anticoagulantes'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '75mg una vez al día', 'Oral',
  'Prevención de eventos aterotrombóticos, post-stent coronario, ACV isquémico',
  'Hemorragia activa, úlcera péptica activa, insuficiencia hepática severa'),

-- ANTIÁCIDOS Y PROTECTORES GÁSTRICOS (56-65)
('Omeprazol 20mg', 'Inhibidor de bomba de protones',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiácidos'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '20mg una vez al día antes del desayuno', 'Oral',
  'Úlcera gástrica y duodenal, reflujo gastroesofágico, esofagitis',
  'Hipersensibilidad, uso concomitante con nelfinavir'),

('Esomeprazol 40mg', 'Inhibidor de bomba de protones, isómero S de omeprazol',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiácidos'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '40mg una vez al día', 'Oral',
  'ERGE, úlcera péptica, síndrome de Zollinger-Ellison',
  'Hipersensibilidad, uso con atazanavir'),

('Pantoprazol 40mg', 'Inhibidor de bomba de protones',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiácidos'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '40mg una vez al día', 'Oral',
  'Úlcera duodenal, úlcera gástrica, reflujo gastroesofágico',
  'Hipersensibilidad, insuficiencia hepática severa'),

('Ranitidina 150mg', 'Antagonista de receptores H2 de histamina',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiácidos'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '150mg dos veces al día', 'Oral',
  'Úlcera péptica, reflujo gastroesofágico, dispepsia',
  'Hipersensibilidad, porfiria aguda'),

('Famotidina 20mg', 'Antagonista de receptores H2',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiácidos'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '20mg una o dos veces al día', 'Oral',
  'Úlcera péptica, ERGE, síndrome de Zollinger-Ellison',
  'Hipersensibilidad, insuficiencia renal severa'),

('Sucralfato 1g', 'Protector de mucosa gástrica',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiácidos'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '1g cuatro veces al día con estómago vacío', 'Oral',
  'Úlcera péptica activa, prevención de úlcera por estrés',
  'Insuficiencia renal crónica, alimentación por sonda'),

('Hidróxido de Aluminio y Magnesio', 'Antiácido combinado',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiácidos'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '10-20ml después de las comidas y al acostarse', 'Oral',
  'Acidez estomacal, dispepsia, reflujo ácido leve',
  'Insuficiencia renal, obstrucción intestinal'),

('Lansoprazol 30mg', 'Inhibidor de bomba de protones',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiácidos'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '30mg una vez al día antes del desayuno', 'Oral',
  'Úlcera duodenal, úlcera gástrica, erradicación de H. pylori',
  'Hipersensibilidad, uso con atazanavir'),

('Dexlansoprazol 60mg', 'IBP de liberación dual',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiácidos'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '60mg una vez al día', 'Oral',
  'Esofagitis erosiva, ERGE sintomático',
  'Hipersensibilidad, insuficiencia hepática severa'),

('Rabeprazol 20mg', 'Inhibidor de bomba de protones',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antiácidos'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '20mg una vez al día', 'Oral',
  'Úlcera duodenal, ERGE, erradicación de H. pylori',
  'Hipersensibilidad'),

-- BRONCODILATADORES (66-70)
('Salbutamol 100mcg', 'Beta-2 agonista de acción corta inhalado',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Broncodilatadores'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '1-2 inhalaciones cada 4-6 horas según necesidad', 'Inhalatoria',
  'Asma, EPOC, broncoespasmo, prevención de broncoespasmo inducido por ejercicio',
  'Hipersensibilidad, taquiarritmias no controladas'),

('Fluticasona/Salmeterol 250/50mcg', 'Corticoide inhalado + beta-2 agonista de acción prolongada',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Broncodilatadores'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '2 inhalaciones dos veces al día', 'Inhalatoria',
  'Asma persistente, EPOC moderado a severo',
  'Infección respiratoria aguda, hipersensibilidad'),

('Budesonida/Formoterol 160/4.5mcg', 'Corticoide + broncodilatador de acción prolongada',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Broncodilatadores'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '1-2 inhalaciones dos veces al día', 'Inhalatoria',
  'Asma, mantenimiento de EPOC',
  'Infecciones no tratadas, tuberculosis activa'),

('Tiotropio 18mcg', 'Anticolinérgico de acción prolongada',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Broncodilatadores'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '1 inhalación una vez al día', 'Inhalatoria',
  'EPOC, mantenimiento de asma en combinación',
  'Hipersensibilidad a atropina, glaucoma de ángulo cerrado'),

('Ipratropio 20mcg', 'Anticolinérgico de acción corta',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Broncodilatadores'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '2 inhalaciones 3-4 veces al día', 'Inhalatoria',
  'EPOC, broncoespasmo agudo en combinación con beta-2',
  'Hipersensibilidad, glaucoma, hipertrofia prostática con retención'),

-- ANTIDEPRESIVOS (71-75)
('Sertralina 50mg', 'Inhibidor selectivo de recaptación de serotonina (ISRS)',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidepresivos'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '50mg una vez al día, puede aumentar hasta 200mg', 'Oral',
  'Depresión mayor, trastorno obsesivo-compulsivo, pánico, ansiedad social',
  'Uso de IMAO, síndrome serotoninérgico, hipersensibilidad'),

('Fluoxetina 20mg', 'ISRS de acción prolongada',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidepresivos'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '20mg una vez al día por la mañana', 'Oral',
  'Depresión mayor, bulimia nerviosa, TOC, trastorno disfórico premenstrual',
  'Uso de IMAO, tioridazina, pimozida'),

('Escitalopram 10mg', 'ISRS, enantiómero activo de citalopram',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidepresivos'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '10mg una vez al día, puede aumentar a 20mg', 'Oral',
  'Depresión mayor, trastorno de ansiedad generalizada, pánico',
  'Uso de IMAO, prolongación QT, hipersensibilidad'),

('Venlafaxina 75mg', 'Inhibidor de recaptación de serotonina y noradrenalina (IRSN)',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidepresivos'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '75mg una o dos veces al día con alimentos', 'Oral',
  'Depresión mayor, ansiedad generalizada, fobia social, pánico',
  'Uso de IMAO, hipertensión no controlada, insuficiencia hepática severa'),

('Amitriptilina 25mg', 'Antidepresivo tricíclico',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antidepresivos'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '25-150mg al día, dosis nocturna', 'Oral',
  'Depresión mayor, dolor neuropático, migraña profilaxis, fibromialgia',
  'Infarto reciente, glaucoma de ángulo cerrado, retención urinaria, IMAO'),

-- ANSIOLÍTICOS (76-80)
('Alprazolam 0.5mg', 'Benzodiacepina de acción intermedia',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Ansiolíticos'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '0.5-1mg tres veces al día según necesidad', 'Oral',
  'Trastorno de ansiedad, crisis de pánico, ansiedad asociada a depresión',
  'Glaucoma de ángulo cerrado, miastenia gravis, insuficiencia respiratoria'),

('Clonazepam 0.5mg', 'Benzodiacepina de acción prolongada',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Ansiolíticos'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '0.5-2mg al día dividido en 2-3 dosis', 'Oral',
  'Trastorno de pánico, epilepsia, trastornos de ansiedad',
  'Glaucoma agudo, insuficiencia hepática severa, depresión respiratoria'),

('Lorazepam 1mg', 'Benzodiacepina de acción intermedia',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Ansiolíticos'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '1-2mg dos o tres veces al día', 'Oral',
  'Ansiedad, insomnio transitorio, premedicación anestésica',
  'Glaucoma de ángulo cerrado, miastenia gravis, apnea del sueño'),

('Diazepam 5mg', 'Benzodiacepina de acción prolongada',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Ansiolíticos'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '5-10mg dos o tres veces al día', 'Oral',
  'Ansiedad, espasmos musculares, convulsiones, abstinencia alcohólica',
  'Miastenia gravis, insuficiencia respiratoria severa, glaucoma'),

('Buspirona 10mg', 'Ansiolítico no benzodiacepínico',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Ansiolíticos'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '10mg dos o tres veces al día', 'Oral',
  'Trastorno de ansiedad generalizada (no para crisis agudas)',
  'Insuficiencia renal o hepática severa, uso de IMAO'),

-- VITAMINAS Y SUPLEMENTOS (81-90)
('Complejo B', 'Vitaminas del complejo B (B1, B2, B3, B5, B6, B12)',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Vitaminas y Suplementos'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '1 cápsula al día con alimentos', 'Oral',
  'Deficiencia de vitaminas B, neuropatía, fatiga, convalecencia',
  'Hipersensibilidad a componentes'),

('Vitamina D3 1000 UI', 'Colecalciferol, vitamina D',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Vitaminas y Suplementos'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '1000-2000 UI una vez al día', 'Oral',
  'Deficiencia de vitamina D, osteoporosis, raquitismo',
  'Hipercalcemia, hipervitaminosis D, cálculos renales'),

('Ácido Fólico 5mg', 'Vitamina B9',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Vitaminas y Suplementos'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '5mg una vez al día', 'Oral',
  'Anemia megaloblástica, embarazo, prevención de defectos del tubo neural',
  'Anemia perniciosa no diagnosticada'),

('Calcio + Vitamina D', 'Suplemento de calcio con vitamina D',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Vitaminas y Suplementos'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '1 tableta dos veces al día con alimentos', 'Oral',
  'Osteoporosis, deficiencia de calcio, menopausia',
  'Hipercalcemia, hipercalciuria, cálculos renales'),

('Hierro 100mg', 'Sulfato ferroso, suplemento de hierro',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Vitaminas y Suplementos'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '100mg una o dos veces al día con estómago vacío', 'Oral',
  'Anemia ferropénica, deficiencia de hierro, embarazo',
  'Hemocromatosis, hemosiderosis, anemia no ferropénica'),

('Omega 3 1000mg', 'Ácidos grasos EPA y DHA',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Vitaminas y Suplementos'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '1-2 cápsulas al día con alimentos', 'Oral',
  'Hipertrigliceridemia, prevención cardiovascular, salud cerebral',
  'Alergia a pescado, trastornos de coagulación no controlados'),

('Vitamina C 1000mg', 'Ácido ascórbico',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Vitaminas y Suplementos'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '1000mg una vez al día', 'Oral',
  'Deficiencia de vitamina C, escorbuto, antioxidante, soporte inmune',
  'Cálculos renales oxálicos, hemocromatosis'),

('Magnesio 400mg', 'Suplemento de magnesio',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Vitaminas y Suplementos'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '400mg una vez al día', 'Oral',
  'Deficiencia de magnesio, calambres musculares, migraña profilaxis',
  'Insuficiencia renal severa, bloqueo cardíaco'),

('Zinc 50mg', 'Suplemento de zinc',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Vitaminas y Suplementos'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '50mg una vez al día con alimentos', 'Oral',
  'Deficiencia de zinc, soporte inmune, cicatrización de heridas',
  'Hipersensibilidad, uso prolongado sin supervisión'),

('Multivitamínico Completo', 'Combinación de vitaminas y minerales esenciales',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Vitaminas y Suplementos'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '1 tableta al día con alimentos', 'Oral',
  'Prevención de deficiencias vitamínicas, convalecencia, embarazo',
  'Hipervitaminosis, hipersensibilidad a componentes'),

-- ANTIVIRALES (91-93)
('Aciclovir 400mg', 'Antiviral para herpes virus',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antivirales'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '400mg tres veces al día por 5-10 días', 'Oral',
  'Herpes simple, herpes zóster, varicela, prevención de recurrencias',
  'Hipersensibilidad, insuficiencia renal severa sin ajuste'),

('Oseltamivir 75mg', 'Inhibidor de neuraminidasa para influenza',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antivirales'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '75mg dos veces al día por 5 días', 'Oral',
  'Influenza A y B, prevención de influenza en contactos',
  'Hipersensibilidad, insuficiencia renal severa'),

('Valaciclovir 500mg', 'Profármaco de aciclovir con mejor biodisponibilidad',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Antivirales'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '500mg-1g dos veces al día según indicación', 'Oral',
  'Herpes zóster, herpes genital, prevención de recurrencias',
  'Hipersensibilidad, insuficiencia renal severa'),

-- DIURÉTICOS (94-96)
('Furosemida 40mg', 'Diurético de asa potente',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Diuréticos'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '40mg una o dos veces al día', 'Oral',
  'Edema cardíaco, edema pulmonar, ascitis, hipertensión resistente',
  'Anuria, hipopotasemia severa, deshidratación, alergia a sulfonamidas'),

('Espironolactona 25mg', 'Diurético ahorrador de potasio, antagonista de aldosterona',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Diuréticos'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '25-100mg al día', 'Oral',
  'Insuficiencia cardíaca, hipertensión, ascitis, hiperaldosteronismo',
  'Hiperpotasemia, insuficiencia renal aguda, enfermedad de Addison'),

('Amilorida/Hidroclorotiazida 5/50mg', 'Combinación diurética ahorradora de potasio',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Diuréticos'),
  'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400',
  '1 tableta una o dos veces al día', 'Oral',
  'Hipertensión arterial, prevención de hipopotasemia',
  'Hiperpotasemia, insuficiencia renal, diabetes mellitus'),

-- CORTICOIDES (97-100)
('Prednisona 20mg', 'Corticoide oral de acción intermedia',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Corticoides'),
  'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400',
  '20-60mg al día en una o varias dosis', 'Oral',
  'Enfermedades inflamatorias, alérgicas, autoinmunes, asma severa',
  'Infecciones sistémicas no tratadas, úlcera péptica activa'),

('Dexametasona 4mg', 'Corticoide de alta potencia y larga duración',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Corticoides'),
  'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400',
  '4-8mg al día en dosis divididas', 'Oral',
  'Edema cerebral, náuseas por quimioterapia, enfermedades inflamatorias severas',
  'Infecciones fúngicas sistémicas, hipersensibilidad'),

('Metilprednisolona 16mg', 'Corticoide de potencia intermedia',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Corticoides'),
  'https://images.unsplash.com/photo-1550572017-4978b78de939?w=400',
  '16-32mg al día en dosis divididas', 'Oral',
  'Artritis reumatoide, lupus, esclerosis múltiple, alergias severas',
  'Infecciones sistémicas no tratadas, vacunación con virus vivos'),

('Betametasona 0.5mg', 'Corticoide de alta potencia',
  (SELECT id FROM categorias_medicamentos WHERE nombre = 'Corticoides'),
  'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400',
  '0.5-5mg al día según gravedad', 'Oral',
  'Enfermedades alérgicas, dermatológicas, reumáticas, hematológicas',
  'Tuberculosis activa, infecciones fúngicas sistémicas, herpes ocular');

-- Mensaje final
SELECT 'Se han insertado 100 medicamentos completos con información verídica' AS mensaje;
